version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/authn-service"
    schedule:
      interval: "daily"
    labels:
      - "triage-required"
    assignees:
      - "wwebster-rr"
    reviewers:
      - "wwebster-rr"
    commit-message:
      prefix: "pip"
    open-pull-requests-limit: 0
